version: '3.9'
services:
  consul: 
    image: hashicorp/consul:1.16
    container_name: consul
    restart: "no"
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - mebike-network
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: truongdz002 
      POSTGRES_DB: test-nestjs
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mebike-network
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./apps/api-gateway/.env
    networks:
      - mebike-network
  auth-service:
    build: 
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - consul
      - postgres-db
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - ./apps/auth-service/.env
    networks:
      - mebike-network

networks:
  mebike-network:
    driver: bridge
volumes:
  postgres_data: