syntax = "proto3";

package package;

service MembershipService {
  rpc CreatePackage (CreatePackageRequest) returns (PackageResponse);
  rpc UpdatePackage (UpdatePackageRequest) returns (PackageResponse);
  rpc GetPackage (GetPackageRequest) returns (PackageResponse);
  rpc GetPackageList (GetPackageListRequest) returns (PackageListResponse);
  rpc TogglePackageStatus (TogglePackageStatusRequest) returns (PackageResponse);
  rpc GetPackagesByIds (GetPackagesByIdsRequest) returns (PackageArrayResponse);
}

message Package {
  string id = 1;
  string name = 2;
  double price = 3;
  int32 maxUsages = 4;
  string usageType = 5;
  string status = 6;
  string createdAt = 7;
  string updatedAt = 8;
}

message CreatePackageRequest {
  string name = 1;
  double price = 2;
  optional int32 maxUsages = 3;
  optional string usageType = 4;
}

message UpdatePackageRequest {
  string id = 1;
  optional string name = 2;
  optional double price = 3;
  optional int32 maxUsages = 4;
  optional string usageType = 5;
  optional string status = 6;
}

message GetPackageRequest {
  string id = 1;
}

message TogglePackageStatusRequest {
  string id = 1;
}

message GetPackagesByIdsRequest {
  repeated string ids = 1;
}

message GetPackageListRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string search = 3;
}

message PackageResponse {
  bool success = 1;
  string message = 2;
  int32 statusCode = 3;
  Package data = 4;
  repeated string errors = 5;
}

message Pagination {
  int32 total = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 totalPages = 4;
}

message PackageListResponse {
  bool success = 1;
  string message = 2;
  repeated Package data = 3;
  Pagination pagination = 4;
  int32 statusCode = 5;
  repeated string errors = 6;
}

message PackageArrayResponse {
  bool success = 1;
  string message = 2;
  repeated Package data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}
