syntax = "proto3";

package rental;

service RentalService {
  rpc CreateRental (CreateRentalRequest) returns (RentalResponse);
  rpc EndRental (EndRentalRequest) returns (RentalResponse);
  rpc GetRental (GetRentalRequest) returns (RentalResponse);
  rpc GetRentalList (GetRentalListRequest) returns (RentalListResponse);
}

message Rental {
  string id = 1;
  string accountId = 2;
  string bikeId = 3;
  string startStationId = 4;
  string endStationId = 5;
  string startTime = 6; // ISO 8601 string
  optional string endTime = 7; // ISO 8601 string
  int32 duration = 8;
  string totalPrice = 9;
  optional string subscriptionId = 10;
  string status = 11;
  string createdAt = 12; // ISO 8601 string
  string updatedAt = 13; // ISO 8601 string
}

message RentalList {
  repeated Rental data = 1;
}

message CreateRentalRequest {
  string accountId = 1;
  string bikeId = 2;
  optional string subscriptionId = 3;
}

message EndRentalRequest {
  string accountId = 1;
  string id = 2;
}

message GetRentalListRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string search = 3;
}

message GetRentalRequest {
  string id = 1;
}

message RentalResponse {
  bool success = 1;
  string message = 2;
  Rental data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}

message Pagination {
  int32 total = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 totalPages = 4;
}

message RentalListResponse {
  bool success = 1;
  string message = 2;
  repeated Rental data = 3;
  Pagination pagination = 4;
  int32 statusCode = 5;
  repeated string errors = 6;
}

message Bike {
  string id = 1;
  string chipId = 2;
  optional Station station = 3;
}

message Station {
  string id = 1;
  optional string name = 2;
  optional string address = 3;
}
