syntax = "proto3";

package station;

service FleetService {
  rpc CreateStation (CreateStationRequest) returns (CreateStationResponse);
  rpc GetStation (GetStationRequest) returns (StationDetailResponse);
  rpc UpdateStation (UpdateStationRequest) returns (UpdateStationResponse);
  rpc GetAllStations (GetAllStationsRequest) returns (StationList);
  rpc GetStationsByIds (GetAllStationsByIdsRequest) returns (StationList);
  rpc UpdateStationStatus (UpdateStationStatusRequest) returns (StationDetailResponse);
}

message CreateStationRequest {
  string name = 1;
  string address = 2;
  string latitude = 3;
  string longitude = 4;
  int32 capacity = 5;
}

message UpdateStationStatusRequest {
  string id = 1;
  string status = 2;
}

message GetAllStationsByIdsRequest {
  repeated string ids = 1;
}

message GetStationRequest {
  string id = 1;
}

message UpdateStationRequest {
  string id = 1;
  optional string name = 2;
  optional string address = 3;
  optional string latitude = 4;
  optional string longitude = 5;
  optional int32 capacity = 6;
}

message GetAllStationsRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string latitude = 3;
  optional string longitude = 4;
  optional string search = 5;
}

message Station {
  string id = 1;
  string name = 2;
  string address = 3;
  string latitude = 4;
  string longitude = 5;
  int32 capacity = 6;
  optional double distance = 7;
  string createdAt = 8; 
  string updatedAt = 9;
  repeated BikeInStation bikes = 10;
  optional int32 availableBike = 11;
  optional int32 totalBike = 12;
  optional int32 bookedBike = 13;
  optional int32 brokenBike = 14;
  optional int32 reservedBike = 15;
  optional int32 maintanedBike = 16;
  optional int32 unavailable = 17;
  string status = 18;
}

message BikeInStation {
  string id = 1;
  string chipId = 2;
  string status = 3;
  optional SupplierInBike supplier = 4;
  string createdAt = 5; 
  string updatedAt = 6;
}

message SupplierInBike {
  string id = 1;
  string name = 2;
  string contactFee = 3;
  string createdAt = 4; 
  string updatedAt = 6;
}

message Pagination {
  int32 total = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 totalPages = 4;
}

message StationList {
  bool success = 1;
  string message = 2;
  repeated Station data = 3;
  Pagination pagination = 4;
  int32 statusCode = 5;
  repeated string errors = 6;
}

message CreateStationResponse {
  bool success = 1;
  string message = 2;
  Station data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message UpdateStationResponse {
  bool success = 1;
  string message = 2;
  Station data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message StationDetailResponse {
  bool success = 1;
  string message = 2;
  Station data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}