syntax = "proto3";

package supplier;

message Supplier {
  string id = 1;
  string name = 2;
  ContactInfo contactInfo = 3;
  string contactFee = 4;
  string status = 5;
  string createdAt = 6; 
  string updatedAt = 7;
  repeated BikeInSupplier bikes = 8;
}

message ContactInfo {
  string phone = 1;
  string address = 2;
}

message BikeInSupplier {
  string id = 1;
  string chipId = 2;
  string status = 3;
  optional StationInBike station = 4;
  string createdAt = 5; 
  string updatedAt = 6;
}

message StationInBike {
  string id = 1;
  string name = 2;
  string address = 3;
  int32 capacity = 4;
  string createdAt = 5; 
  string updatedAt = 6;
}

message UpdateSupplierRequest {
  string id = 1;
  optional string name = 2;
  optional string phone = 3;
  optional string address = 4;
  optional string contactFee = 5;
}

message GetSupplierRequest {
  string id = 1;
}

message UpdateSupplierResponse {
  bool success = 1;
  string message = 2;
  Supplier data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message SupplierDetailResponse {
  bool success = 1;
  string message = 2;
  Supplier data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}

message Pagination {
  int32 total = 1;
  int32 page = 2;
  int32 limit = 3;
  int32 totalPages = 4;
}

message SuppliersResponse {
  bool success = 1;
  string message = 2;
  repeated Supplier data = 3;
  Pagination pagination = 4;
  int32 statusCode = 5;
  repeated string errors = 6;
}

message GetAllSupplierRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string search = 3;
}

message ChangeSupplierStatusRequest {
  string id = 1;
  string status = 2;
}

message SupplierStats {
  int32 totalSupplier = 1;
  int32 totalSupplierActive = 2;
  int32 totalSupplierInactive = 3;
}

message SupplierStatsResponse {
  bool success = 1;
  string message = 2;
  SupplierStats data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}

message CreateSupplierRequest {
  string name = 1;
  string phone = 2;
  string address = 3;
  string contactFee = 4;
}

message CreateSupplierResponse {
  bool success = 1;
  string message = 2;
  Supplier data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message GetSupplierByIdsRequest {
  repeated string ids = 1;
}

service FleetService {
  rpc GetSupplier(GetSupplierRequest) returns (SupplierDetailResponse);
  rpc UpdateSupplier(UpdateSupplierRequest) returns (UpdateSupplierResponse);
  rpc GetAllSuppliers(GetAllSupplierRequest) returns (SuppliersResponse);
  rpc ChangeSupplierStatus(ChangeSupplierStatusRequest) returns (UpdateSupplierResponse);
  rpc GetSupplierStats(Empty) returns (SupplierStatsResponse);
  rpc CreateSupplier(CreateSupplierRequest) returns (CreateSupplierResponse);
  rpc GetSupplierByIds(GetSupplierByIdsRequest) returns (SuppliersResponse);
}

message Empty {}
