syntax = "proto3";

package user;

import "google/protobuf/timestamp.proto";

message User {
  string id = 1;
  string accountId = 2;
  string name = 3;
  int32 YOB = 4;
  string verify = 5;
  string role = 6;
  string status = 7;
  string phone = 8;
  google.protobuf.Timestamp createdAt = 9; 
  google.protobuf.Timestamp updatedAt = 10;
}


message UpdateUserRequest {
  string id = 1;
  optional string name = 2;
  optional int32 YOB = 3;
  optional string phone = 4;
}

message GetUserRequest {
  string id = 1;
}

message UpdateUserResponse {
  bool success = 1;
  string message = 2;
  User data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message UserDetailResponse {
  bool success = 1;
  string message = 2;
  User data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}

message UsersResponse {
  bool success = 1;
  string message = 2;
  repeated User data = 3;
  int32 total = 4;
  int32 page = 5;
  int32 limit = 6;
  int32 totalPages = 7;
  int32 statusCode = 8;
  repeated string errors = 9;
}

message GetAllUserRequest {
  int32 page = 1;
  int32 limit = 2;
}

message ChangeStatusRequest {
  string accountId = 1;
  string status = 2;
}

message UserStats {
  int32 totalUsers = 1;
  int32 totalUser = 2;
  int32 totalUserUnverfied = 3;
  int32 totalStaff = 4;
  int32 totalAdmin = 5;
  int32 totalSos = 6;
}

message UserStatsResponse {
  bool success = 1;
  string message = 2;
  UserStats data = 3;
  int32 statusCode = 4;
  repeated string errors = 5;
}


service UserService {
  rpc GetUser(GetUserRequest) returns (UserDetailResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
  rpc GetAllUsers(GetAllUserRequest) returns (UsersResponse);
  rpc ChangeStatus(ChangeStatusRequest) returns (UpdateUserResponse);
  rpc GetUserStats(Empty) returns (UserStatsResponse);
}

message Empty {}
