syntax = "proto3";

package wallet;

service PaymentService {
  rpc CreateWallet (CreateWalletRequest) returns (GetWalletResponse);
  rpc GetWallet (GetWalletRequest) returns (GetWalletResponse);
  rpc GetAllWallets (GetAllWalletsRequest) returns (GetAllWalletsResponse);
  rpc ChangeWalletStatus (ChangeWalletStatus) returns (GetWalletResponse);
}

message CreateWalletRequest {
  string accountId = 1;
}

message Wallet {
  string id = 1;
  string accountId = 2;
  int32 balance = 3;
  string status = 4;
  string createdAt = 5; 
  string updatedAt = 6;
}

message GetWalletRequest {
  string accountId = 1;
}

message GetWalletResponse {
  bool success = 1;
  string message = 2;
  Wallet data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message GetAllWalletsRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string search = 3;
}

message GetAllWalletsResponse {
  bool success = 1;
  string message = 2;
  repeated Wallet data = 3;
  repeated string errors = 4;
  int32 statusCode = 5;
}

message ChangeWalletStatus {
  string id = 1;
  string status = 2;
}